### ISSUE TITLE
Prompts for sudo password

### ISSUE THREAD

**Issue by Anomalocaridid** [kuche1/minq-checkupdates-aur#1]
When I run minq-checkupdates-aur, it prompts for my sudo password. However, it seems to show updates anyways if I press Ctrl+C to cancel at the password prompt.

I am using the Sway edition of EndeavourOS, my shell is zsh 5.8.1, and I installed minq-checkupdates-aur from the AUR using paru.

**Comment by kuche1** [comment]
This is very strange. I am currently using EndeavourOS BSPWM and I cannot reproduce the issue. Can you check if this is still an issue? If yes I have something in mind that might solve the problem.

**Comment by Anomalocaridid** [comment]
It is still an issue.

**Comment by kuche1** [comment]
I have pushed an update, please see if the problem is fixed now

**Comment by Anomalocaridid** [comment]
It works now! Thank you!

**Comment by kuche1** [comment]
Happy to hear!
